const fs = require('fs');

// destination.txt will be created or overwritten by default.

const files = [
  'canva-art-event-flyer-MADKJwTjcG4.webp',
  'canva-dark-blue-and-yellow-space-themed-science-flyer-MAC7mqPbQK8.webp',
  'canva-black-and-gold-christmas-party-flyer-MAC5DgISwgk.webp',
  'canva-blue-illustrated-heart-health-fair-flyer-MAC7m1QGUWA.webp',
  'canva-black-and-yellow-icon-sports-flyer-MAC5t7rcTo0.webp',
  'canva-beige-photo-food-drive-flyer-MAC4DTDfljc.webp',
  'canva-bike-themed-event-flyer-MADKJ_Pquvo.webp',
  'canva-black-and-blue-lines-pattern-food-drive-flyer-MAC3TYAY1fE.webp',
  'canva-green-and-orange-tent-flyer-summer-camp-flyer-MAC3TSOmKhg.webp',
  'canva-blue-yellow-and-orange-leaves-fall-festival-flyer-MAC3ZKCrIds.webp',
  'canva-black-and-yellow-tent-summer-camp-flyer-MAC5t7rVvJ4.webp',
  'canva-orange-bordered-photo-food-drive-flyer-MAC3TTAYPR8.webp',
  'canva-event-flyer-MADKJzVJFo8.webp',
  'canva-black-and-yellow-volleyball-icons-sports-flyer-MAC3X5T2nN8.webp',
  'canva-blue-photo-collage-food-drive-flyer-MAC7mgTLvk0.webp',
  'canva-blue-orange-border-diagonal-line-food-drive-flyer-MAC3TTBdtfM.webp',
  'canva-orange-&-white-bold-creative-sport-football-tryouts-flyer-MAC6S8qYjo8.webp',
  'canva-green-vegetable-flatlay-food-flyer-MAC6lYFykfE.webp',
  'canva-brown-and-grey-illustrated-icons-summer-camp-flyer-MAC3XzSjncw.webp',
  'canva-orange-and-black-football-party-sports-flyer-MAC3XxQFTlU.webp',
  'canva-black-and-gold-all-white-party-flyer-MAC7msY4lpw.webp',
  'canva-white-with-donuts-bake-sale-flyer-MAC4CsQClwE.webp',
  'canva-green-dog-with-shades-pet-fundraising-flyer-MAC4XeJseVQ.webp',
  'canva-coral-&-black-photo-birthday-flyer-MAC4Cw5ADUo.jpg',
  'canva-green-illustrated-bake-sale-flyer-MAC4C3eiDho.webp',
  'canva-cream-and-blue-cupcake-fundraiser-flyer-MAC5EBZuooM.webp',
  'canva-orange-mountains-summer-camp-flyer-MAC3Y6D0AFU.webp',
  'canva-purple-and-green-earth-volunteer-flyer-MAC7mtoG_Mk.webp',
  'canva-blue-vaccine-photo-health-fair-flyer-MAC5uz44Wss.webp',
  'canva-black-and-white-collage-fashion-show-flyer-MAC4DkO_3zY.webp',
  'canva-orange-with-monkey-llustration-birthday-flyer-MAC5t3-JpG8.webp',
  'canva-green-fall-festival-event-flyer-MAC7mpRJwkg.webp',
  'canva-colorful-confetti-background-birthday-celebration-event-flyer-MAC7mrsHwDA.jpg',
  'canva-black-and-orange-leaves-fall-festival-flyer-MAC3X3Fhbtc.webp',
  'canva-cream-and-purple-icons-food-drive-flyer-MAC5t38U8lM.webp',
  'canva-orange-and-red-leaves-fall-festival-flyer-MAC5t4eyqbI.webp',
  'canva-pink-and-turquoise-illustrated-volleyball-sports-flyer-MAC3TfTE7XM.webp',
  'canva-orange-and-black-vector-job-fair-flyer-MAC7m4cpzFQ.webp',
  'canva-blue-and-cream-grungy-popcorn-movie-night-flyer-MAC3TVsjX7s.webp',
  'canva-green-and-red-cookie-exchange-consumer-personal-flyer-MADI6f2rupo.webp',
  'canva-green-medicine-icons-health-fair-flyer-MAC4Dj6eGos.webp',
  'canva-charcoal-photo-food-drive-flyer-MAC3ToeVKl4.webp',
  'canva-white-and-charcoal-all-white-party-flyer-MAC7mt5CsZA.webp',
  "canva-dark-purple-orange-witch's-hat-halloween-flyer-MAC5D3BIrJY.webp",
  'canva-chili-cook-off-event-flyer-MADKJ20E4jk.webp',
  'canva-orange-and-white-icons-sports-flyer-MAC3TYnQPGY.webp',
  'canva-beige-scissors-icon-lines-volunteer-flyer-MAC7WcpqvLI.webp',
  'canva-blue-and-green-leaves-festival-flyer-MAC6k18asQo.webp',
  'canva-yellow-and-black-jazz-night-saxophone-illustration-concert-flyer-MAC4_opPoG0.webp',
  'canva-green-limes-food-drive-flyer-MAC3X-aJ3LE.webp',
  'canva-red-and-cream-illustration-sale-retail-flyer-MADI6Zevgis.webp',
  'canva-pastel-popsicle-summer-festival-flyer-MAC7mwERtvk.webp',
  'canva-black-and-yellow-basketball-game-sports-flyer-MAC3TYyZW7g.webp',
  'canva-yellow-music-fundraiser-flyer-MAC5EBEsPLU.webp',
  'canva-blue-overlay-photo-job-fair-flyer-MAC7m-IHy2k.webp',
  'canva-colorful-floral-doodle-background-flyer-MAC5DkfGmqY.webp',
  'canva-dark-blue-cream-and-red-tickets-and-stars-movie-night-flyer-MAC7mpJQ4j8.webp',
  'canva-red-saxophone-jazz-concert-flyer-MAC4_jMH4Zc.webp',
  'canva-dark-blue-photo-medical-health-fair-flyer-MAC7WYh2mIQ.webp',
  'canva-blue-orange-leaves-fall-festival-flyer-MAC3Ta-ko3M.webp',
  'canva-blue-with-tent-and-trees-summer-camp-flyer-MADLhW3Znkw.webp',
  'canva-creams-carrots-stars-illustration-easter-flyer-MAC4WuYXyV4.webp',
  'canva-blue-illustration-art-gallery-raffle-flyer-MAC4XK0cokg.webp',
  'canva-blue-dots-and-rabbit-illustration-easter-flyer-MAC4WvNSUnk.jpg',
  'canva-blue-and-peach-girl-photo-birthday-flyer-MAC3TT-TnZw.webp',
  'canva-modern-elegant-colorful-cupcakes-bake-sale-flyer-MAC4C0X6lvc.webp',
  'canva-red-and-cream-block-party-flyer-MAC5uGwBvFY.webp',
  'canva-neon-green-soccer-ball-sports-flyer-MAC3TekBSco.webp',
  'canva-red-hockey-game-sports-flyer-MAC5P8evlMw.webp',
  'canva-black-and-orange-basketball-fundraiser-flyer-MAC5Lp6K9A8.webp',
  "canva-coral-flower-photo-mother's-day-flyer-MAC4C_nGiBg.webp",
  'canva-blue-and-orange-leaves-fall-festival-flyer-MAC3TUavprc.webp',
  'canva-dark-blue-square-pattern-job-fair-flyer-MAC4WpalR-Y.webp',
  'canva-yellow-ice-cream-parlor-fundraiser-flyer-MAC5D0kbNIw.webp',
  'canva-monochromatic-urban-photography-background-workshop-flyer-MAC4XMMDHbk.webp',
  'canva-teal-and-coral-triangle-confetti-village-yard-sale-flyer-MAC4XdUUMVw.webp',
  'canva-teal-vector-white-elephant-flyer-MADLiGY128A.webp',
  'canva-pink-overlay-flower-festival-flyer-MAC4DWCq5Dk.webp',
  'canva-monochrome-model-photo-fashion-show-flyer-MAC5vQWghwE.webp',
  'canva-orange-and-green-fiesta-party-flyer-MAC7mj1J6Xs.webp',
  'canva-navy-woman-photo-fashion-show-flyer-MAC5vawSZY4.webp',
  'canva-medium-aquamarine-building-job-fair-flyer-MAC5uiumats.webp',
  'canva-orange-food-illustration-volunteer-flyer-MAC7WVZ7fZ0.webp',
  'canva-black-street-party-flyer-MAC5PxY69Mk.webp',
  'canva-blue-eggs-icons-easter-flyer-MAC5uB9x6oE.webp',
  'canva-pink-illustrated-eggs-in-basket-easter-flyer-MAC6lHZC5Is.webp',
  'canva-yellow-tree-cutout-fun-run-fundraiser-flyer-MAC4XNvCfaM.webp',
  'canva-bright-pink-photo-music-festival-flyer-MAC50_8yy5U.webp',
  'canva-blue-christmas-birds-festive-holidays-flyer-MAC4XH26kEo.webp',
  'canva-teal-pink-stars-cupcake-bake-sale-flyer-MAC3TXvIpQI.webp',
  'canva-red-yellow-colorful-90s-photo-skate-party-flyer-MAC5uH-riCQ.webp',
  'canva-black-and-white-grunge-fashion-show-flyer-MAC5uhUj7q0.webp',
  'canva-orange-autumn-leaves-pattern-fall-festival-flyer-MAC3Tal7QLw.webp',
  'canva-brown-illustration-dancers-ballet-dance-flyer-MAC4XLVJiIg.webp',
  'canva-blue-and-yellow-space-birthday-flyer-MAC2uz7lomQ.webp',
  'canva-yellow-green-scientist-science-flyer-MAC6lHuacDE.webp',
  'canva-black-modern-exhibit-volunteer-flyer-MAC7WViArkY.webp',
  'canva-blue-photo-health-fair-flyer-MAC4WqK5At4.webp',
  "canva-coral-floral-mother's-day-celebration-flyer-MAC7mihIXWc.jpg",
  'canva-dark-maroon-and-yellow-beach-party-flyer-MAC5p09I7SY.webp',
]

const inputPath = "/Users/keslert/Projects/Research/DesignQ/sketch/canva-2019-01-16"
const outputPath = "/Users/keslert/Projects/Research/DesignQ/sketch/canva-top-100-of-313"

files.forEach(file => {
  fs.copyFile(`${inputPath}/${file}`, `${outputPath}/${file}`, (err) => {
    if (err) throw err;
    console.log('source.txt was copied to destination.txt');
  });
})
